[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = COM5
monitor_port = COM5

lib_deps =
    https://github.com/ElectronicCats/mpu6050
    https://github.com/adafruit/Adafruit_BME680
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    sparkfun/SparkFun TB6612FNG Motor Driver Library @ ^1.0.0